CREATE TABLE datawarehouse.pipeline_weather_data (

CIDADE VARCHAR(100),
DATA_HORA TIMESTAMP,
TEMPERATURA_CELSIUS FLOAT,
PRECIP_MM FLOAT,
VELICIDADE_VENTO_MS FLOAT

);

DROP TABLE datawarehouse.teste

SELECT * FROM datawarehouse.teste